### PR TITLE
18-animated-symbol-fix

### LINKED ISSUE #18: How to set different color for each animatedCanvasBezierStyle points ?
Hello, 

First of all I want to thank you for this wonderful lib :)

I'm trying to set a different color for each point of `animatedCanvasBezierStyle ` as like `canvasBezierStyle` with the option _classBreakInfos_ but it doesn't work. I also tried to modify the  function of `_animateCanvasLineSymbol` for _symbolObject.strokeStyle_ but it's not better...

Like bellow, I would like to set color of animated point with the same color of lines.

image

Could someone help me please ?

Best regards.

### PR DESCRIPTION
**Pull request by jwasilgeo**
resolves #18

### CODE REVIEW

**Comment by jwasilgeo** [comment]
@oijkn I will merge in the fix for your issue #18.  Please try again and let me know how it goes.

**Comment by oijkn** [comment]
@jwasilgeo Thank you very much for this update, you roxx :) I will try it ASAP.

BR.

**Comment by oijkn** [comment]
@jwasilgeo I tried your last code but all animated symbol steal in grey if I set `animatedCanvasBezierStyle` and red if I comment off it. Can you provide me a valid example, please ? Thx you in advance :)

**Comment by jwasilgeo** [comment]
Can you give me an example of your symbol settings that aren't working?

Also, did you use a `lineDashOffsetSize`, such as for the default style here?  That is necessary I believe.
https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/src/CanvasFlowmapLayer.js#L62

**Comment by oijkn** [comment]
@jwasilgeo In my previous example https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/issues/18#issuecomment-498412545 I tried to use your latest code and all symbol are grey. If I use `animatedCanvasBezierStyle` custom settings or default.

In the screenshot of your https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/issues/18#issuecomment-498712089 I can see différents symbols colors. How did you do, please ?

**Comment by jwasilgeo** [comment]
In your codepen demo, try to change this block of code:

```javascript
    animatedCanvasBezierStyle: {
      type: "simple",
      symbol: {
        strokeStyle: "rgba(255, 255, 255, 0.5)",
        lineWidth: 3,
        lineDashOffsetSize: 4,
        lineCap: "round",
        shadowColor: "rgba(255, 255, 255, 0.5)",
        shadowBlur: 2
      }
    },
```

to this block instead:

```javascript
    animatedCanvasBezierStyle: {
      type: "classBreaks",
      field: "rand_num",
      classBreakInfos: [
        {
          classMinValue: 0,
          classMaxValue: 30,
          symbol: {
            strokeStyle: "rgba(255, 0, 0, 0.8)",
            lineWidth: 3,
            lineDashOffsetSize: 4,
            lineCap: "round",
            shadowColor: "rgba(255, 0, 0, 0.8)",
            shadowBlur: 1.5
          }
        },
        {
          classMinValue: 31,
          classMaxValue: 60,
          symbol: {
            strokeStyle: "rgba(255, 165, 0, 0.8)",
            lineWidth: 3,
            lineDashOffsetSize: 4,
            lineCap: "round",
            shadowColor: "rgba(255, 165, 0, 0.8)",
            shadowBlur: 1.5
          }
        },
        {
          classMinValue: 61,
          classMaxValue: 100,
          symbol: {
            strokeStyle: "rgba(128, 165, 0, 0.8)",
            lineWidth: 3,
            lineDashOffsetSize: 4,
            lineCap: "round",
            shadowColor: "rgba(128, 165, 0, 0.8)",
            shadowBlur: 1.5
          }
        }
      ]
    },
```

Seems to work well for me.

**Comment by oijkn** [comment]
Great !! Amazing !! Thank you a lot dude :)

**Comment by jwasilgeo** [comment]
Very happy to hear it!  Let me know if you have a publicly available site you can share when you are finished as I'd be interested to see how it looks in the end.

**Comment by oijkn** [comment]
It might be complicated because it's a project for my company and some data is critical.
So I couldn't share this with the community but I'd be happy to show you the final result.

**Pull request merged**
