### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ilyankou**
Fix `originAndDestinationFieldIds` example so that it corresponds to the example of a single GeoJSON feature presented above

### CODE REVIEW

**Comment by jwasilgeo** [comment]
Hi @ilyankou thanks for your PR and interest in this project!  I appreciate your proposed change, but for now I am thinking about leaving the current README unaltered.  The `originAndDestinationFieldIds` in this section is [extracted from the source code (line 154 above)](https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/pull/14/files#diff-04c6e90faac2675aa89e2176d2eec7d8L154) and is intended to be generic as part of the API documentation.

From your experience using this library are there other aspects of the README that could be changed instead to make things more clear and easier to understand for other developers?  For example, maybe the "Example of a single GeoJSON point feature" above in the README could become generic.

**Comment by ilyankou** [comment]
@jwasilgeo I think it should be enough to change `origin_city_id` to `origin_id` and `destination_city_id` to `destination_id` in the GeoJSON point feature example to add consistency with the rest of the examples (and have it running without errors by simply copy-pasting).

The docs were good enough for me to get started in less than an hour. Thanks so much for the product!

**Comment by jwasilgeo** [comment]
Thank you! I appreciate your feedback!

If you are interested in making this change I’d still be happy to welcome your PR.

**Comment by ilyankou** [comment]
@jwasilgeo I changed the example GeoJSON properties to match the `originAndDestinationFieldIds`, minor update but it should let the code run when copy-pasted.

**Comment by jwasilgeo** [comment]
@ilyankou thank you very much!

**Pull request merged**
